In [1]:
import numpy as np

In [2]:
np.exp(1)

2.7182818284590451

In [15]:
w = np.array([[0, 1]])
x = np.array([[1, 2.5],
             [1, 0.3],
             [1, 2.8],
             [1, 0.5]])
print np.transpose(w)
print w * x
print np.dot(w, np.transpose(x))
#1/(1 + (np.exp()))

[[0]
 [1]]
[[ 0.   2.5]
 [ 0.   0.3]
 [ 0.   2.8]
 [ 0.   0.5]]
[[ 2.5  0.3  2.8  0.5]]


In [25]:
def logistic(x):
    return 1/(1 + (np.exp(-x)))

print logistic(2.5)
print logistic(.3)
print logistic(2.8)
print logistic(.5)


logistic(2.5) * (1 - logistic(0.3)) *  logistic(2.8) *  logistic(0.5)

0.924141819979
0.574442516812
0.942675824101
0.622459331202


0.23076514147414118

In [24]:
2.5*(1 - logistic(2.5)) + 0.3 * (0 - logistic(0.3)) + 2.8 * (1 - logistic(2.8)) + 0.5*(1-logistic(0.5))

0.36659072192551606